apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: israel-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/Israel14029/deployment-yaml.git
    targetRevision: main
    path: deployment-yaml  # Make sure this exists!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


